/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package mco2_ang_balbastro;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Displays the screen where the Player can be created.
 * 
 * @author ANG, JEREMIAH MAXWELL
 * @author BALBASTRO, LIANNE MAXENE
 * @version 1.0
 */
public class CharacterCreation extends javax.swing.JFrame {
    
    private Player CPlayer = new Player();

    /**
     * Sole Constructor.
     * Creates new form CharacterCreation and makes the confirm creation button invisible.
     */
    public CharacterCreation() {
        initComponents();
        bConfirm.setVisible(false); // Make bConfirm initially invisible
        
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneDetails = new javax.swing.JScrollPane();
        txtCharDetails = new javax.swing.JTextPane();
        tfName = new javax.swing.JTextField();
        boxSelectJob = new javax.swing.JComboBox<>();
        JobClassImage = new javax.swing.JLabel();
        bEnter = new javax.swing.JButton();
        bConfirm = new javax.swing.JButton();
        bBack = new javax.swing.JButton();
        labCharacterCreation = new javax.swing.JLabel();
        labCharacter = new javax.swing.JLabel();
        labCreation = new javax.swing.JLabel();
        panelUnderline = new javax.swing.JPanel();
        labBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCharDetails.setEditable(false);
        txtCharDetails.setBackground(new java.awt.Color(230, 210, 135));
        txtCharDetails.setFont(new java.awt.Font("STZhongsong", 0, 14)); // NOI18N
        txtCharDetails.setForeground(new java.awt.Color(255, 255, 255));
        paneDetails.setViewportView(txtCharDetails);

        getContentPane().add(paneDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 230, 210));

        tfName.setBackground(new java.awt.Color(230, 210, 135));
        tfName.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tfName.setForeground(new java.awt.Color(93, 90, 74));
        tfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfName.setText("Input Name");
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 230, 60));

        boxSelectJob.setBackground(new java.awt.Color(230, 210, 135));
        boxSelectJob.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        boxSelectJob.setForeground(new java.awt.Color(93, 90, 74));
        boxSelectJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "        Select Job Class", "Vagabond", "Samurai", "Warrior", "Hero", "Astrologer", "Prophet" }));
        boxSelectJob.setFocusable(false);
        boxSelectJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSelectJobActionPerformed(evt);
            }
        });
        getContentPane().add(boxSelectJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 230, 60));
        getContentPane().add(JobClassImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 190, 380));

        bEnter.setBackground(new java.awt.Color(136, 160, 139));
        bEnter.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        bEnter.setForeground(new java.awt.Color(255, 255, 255));
        bEnter.setText("ENTER");
        bEnter.setFocusable(false);
        bEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnterActionPerformed(evt);
            }
        });
        getContentPane().add(bEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 110, 30));

        bConfirm.setBackground(new java.awt.Color(136, 160, 139));
        bConfirm.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        bConfirm.setForeground(new java.awt.Color(255, 255, 255));
        bConfirm.setText("CONFIRM");
        bConfirm.setFocusable(false);
        bConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(bConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 230, 30));

        bBack.setBackground(new java.awt.Color(204, 130, 130));
        bBack.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        bBack.setForeground(new java.awt.Color(255, 255, 255));
        bBack.setText("BACK");
        bBack.setFocusable(false);
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });
        getContentPane().add(bBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 110, 30));

        labCharacterCreation.setBackground(new java.awt.Color(255, 255, 255));
        labCharacterCreation.setFont(new java.awt.Font("Serif", 1, 58)); // NOI18N
        labCharacterCreation.setForeground(new java.awt.Color(113, 143, 140));
        labCharacterCreation.setText("HARACTER CREATIO");
        getContentPane().add(labCharacterCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        labCharacter.setFont(new java.awt.Font("Serif", 1, 78)); // NOI18N
        labCharacter.setForeground(new java.awt.Color(113, 143, 140));
        labCharacter.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labCharacter.setText("C");
        labCharacter.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(labCharacter, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 80));

        labCreation.setFont(new java.awt.Font("Serif", 1, 78)); // NOI18N
        labCreation.setForeground(new java.awt.Color(113, 143, 140));
        labCreation.setText("N");
        getContentPane().add(labCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        panelUnderline.setBackground(new java.awt.Color(113, 143, 140));
        panelUnderline.setForeground(new java.awt.Color(113, 143, 140));
        getContentPane().add(panelUnderline, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 600, -1));

        labBackground.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        labBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Character Selection.jpg"))); // NOI18N
        getContentPane().add(labBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 940, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed

    }//GEN-LAST:event_tfNameActionPerformed

    private void boxSelectJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSelectJobActionPerformed
        String selectedJob = (String) boxSelectJob.getSelectedItem();
        if (selectedJob == null) {
            return; // In case nothing is selected or the model is empty
        }

        String imagePath;
        
        switch (selectedJob.trim()) { // Using trim() to ensure we match correctly
            case "Vagabond" -> imagePath = "/mco1_ang_balbastro/Backgrounds/Job Classes/Vagabond.jpg";
            case "Samurai" -> imagePath = "/mco1_ang_balbastro/Backgrounds/Job Classes/Samurai.jpg";
            case "Warrior" -> imagePath = "/mco1_ang_balbastro/Backgrounds/Job Classes/Warrior.jpg";
            case "Hero" -> imagePath = "/mco1_ang_balbastro/Backgrounds/Job Classes/Hero.jpg";
            case "Astrologer" -> imagePath = "/mco1_ang_balbastro/Backgrounds/Job Classes/Astrologer.jpg";
            case "Prophet" -> imagePath = "/mco1_ang_balbastro/Backgrounds/Job Classes/Prophet.jpg";
            default -> {
                JOptionPane.showMessageDialog(this, "No image available for this job class.", "Image Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        // Using trim() to ensure we match correctly

        // Set the image icon to JobClassImage
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
            JobClassImage.setIcon(icon);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to set job class image: " + e.getMessage(), "Image Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boxSelectJobActionPerformed

    /**
     * Checks user inputs before setting the Player's fields.
     * Makes the Confirm button reappear when user inputs are valid.
     * @param evt 
     */
    private void bEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnterActionPerformed
        String strName = tfName.getText();
        String strClass = (String)boxSelectJob.getSelectedItem();
        
        int nClassStats[][] = {{9, 9, 8, 7, 6, 7}, //[0] Class base levels
                          {15, 13, 9, 11, 14, 6}, //[1] Vagabond
                          {12, 15, 9, 13, 12, 8}, //[2] Samurai
                          {11, 16, 10, 11, 10, 8},//[3] Warrior
                          {14, 9, 7, 12, 16, 8},  //[4] Hero
                          {9, 12, 16, 9, 8, 7},   //[5] Astrologer
                          {10, 10, 7, 8, 11, 16}};//[6] Prophet
        
        //if no name or no job class is selected, show error message
        if(strName.isEmpty() || strName.equals("Input Name") && boxSelectJob.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Please pick your Name and Job Class", "Empty fields", JOptionPane.ERROR_MESSAGE);
            tfName.setText("Input Name");
        } 
        else if(strName.isEmpty() || strName.equals("Input Name")){
            JOptionPane.showMessageDialog(this, "Enter your name bro", "Empty name field", JOptionPane.ERROR_MESSAGE);
            tfName.setText("Input Name");
        } 
        else if(boxSelectJob.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Pick your class bro", "Empty class field", JOptionPane.ERROR_MESSAGE);
        }
        else {
            
        CPlayer.setName(strName);
        CPlayer.setJobClass(strClass);
        CPlayer.setPlayerLevel(nClassStats[0][boxSelectJob.getSelectedIndex() - 1]); //-1 because classes start with [1]
        
        //Set Statistics
        CPlayer.setHealth(nClassStats[boxSelectJob.getSelectedIndex()][0]);
        CPlayer.setDexterity(nClassStats[boxSelectJob.getSelectedIndex()][1]);
        CPlayer.setIntelligence(nClassStats[boxSelectJob.getSelectedIndex()][2]);
        CPlayer.setEndurance(nClassStats[boxSelectJob.getSelectedIndex()][3]);
        CPlayer.setStrength(nClassStats[boxSelectJob.getSelectedIndex()][4]);
        CPlayer.setFaith(nClassStats[boxSelectJob.getSelectedIndex()][5]);
        
        
        // Displaying of Player details in txtCharDetails
        txtCharDetails.setContentType("text/html"); // Allows HTML content
            String htmlContent = "<html>" +
                    "<body>" +
                    "<div style='text-align: center;'><b>-- Current Character Info --</b></div><br/>" +
                    "<div><b>Name:</b> " + CPlayer.getName() + "</div>" +
                    "<div><b>Job Class:</b> " + CPlayer.getJobClass() + "</div>" +
                    "<div><b>Level:</b> " + CPlayer.getPlayerLevel() + "</div>" +
                    
                    "<div><b>HP:</b> " + CPlayer.getHealth() + "</div>" +
                    "<div><b>DEXTERITY:</b> " + CPlayer.getDexterity() + "</div>" +
                    "<div><b>INTELLIGENCE:</b> " + CPlayer.getIntelligence() + "</div>" +
                    "<div><b>ENDURANCE:</b> " + CPlayer.getEndurance() + "</div>" +
                    "<div><b>STRENGTH:</b> " + CPlayer.getStrength() + "</div>" +
                    "<div><b>FAITH:</b> " + CPlayer.getFaith() + "</div>" +
                    "</body></html>";
txtCharDetails.setText(htmlContent);
        
        bConfirm.setVisible(true);
    }
    
    tfName.setText("");
    }//GEN-LAST:event_bEnterActionPerformed

    /**
     * Returns to the Title Menu once the Back Button is pressed.
     * @param evt 
     */
    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new TitleMenu().setVisible(true);
            this.dispose();
        });
        
    }//GEN-LAST:event_bBackActionPerformed

    /**
     * Proceeds to the Game Lobby screen once the Confirm Button is pressed.
     * @param evt 
     */
    private void bConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GameLobby(CPlayer).setVisible(true);
            this.dispose(); //closes CharacterCreation screen
        });
        
    }//GEN-LAST:event_bConfirmActionPerformed

            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JobClassImage;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bConfirm;
    private javax.swing.JButton bEnter;
    private javax.swing.JComboBox<String> boxSelectJob;
    private javax.swing.JLabel labBackground;
    private javax.swing.JLabel labCharacter;
    private javax.swing.JLabel labCharacterCreation;
    private javax.swing.JLabel labCreation;
    private javax.swing.JScrollPane paneDetails;
    private javax.swing.JPanel panelUnderline;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextPane txtCharDetails;
    // End of variables declaration//GEN-END:variables
}
