/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mco2_ang_balbastro;

/**
 * Displays the Elden Throne area.
 * 
 * @author ANG, JEREMIAH MAXWELL
 * @author BALBASTRO, LIANNE MAXENE
 * @version 2.0
 */
public class EldenThrone extends Area {

    /**
     * Sole constructor.
     * Requires Player upon creation.
     *
     * @param CPlayer
     */
    public EldenThrone(Player CPlayer) {
        super(3, CPlayer, 3, "Elden Throne");
        initComponents();
        
        createLabelList();
        this.fmFloor1.setVisible(true);
        
        
        //from the Area parent
        //int parameters: floor num, # of fast, # of spawn, # of boss, # of door
        generateFloor(0, 1, 1, 0, 1);
        generateFloor(1, 0, 0, 1, 2);
        generateFloor(2, 0, 8, 0, 1);
        
        
        associateLabels(this.nFloorCount); //from the Area parent
        initializeKeyListener();  
        
        this.fmFloor1.setFocusable(true);
        this.fmFloor1.requestFocusInWindow();  
        
    }
    
    private void checkCreditsTile(){
        boolean isTouchingCredits = CFloors.get( 2 ).getPlayerSprite().getBounds().intersects( labCredit.getBounds());
    }
    
    /**
     * Puts JLabels of tiles into an array of JLabels.
     */
    private void createLabelList(){
        //List of Floor JFrames
        this.CFloors.get(0).setFloorFrames(fmFloor1);
        this.CFloors.get(0).getFloorBack().add(labFloorBack1A);
        
        this.CFloors.get(1).setFloorFrames(fmFloor2);
        this.CFloors.get(1).getFloorBack().add(labFloorBack2A);
        
        this.CFloors.get(2).setFloorFrames(fmFloor3);
        this.CFloors.get(2).getFloorBack().add(labFloorBack3);
        
        addScreenDetails(this.CFloors);
        
        //List of Tile JLabels
        
        //Floor 1
        this.CFloors.get(0).getTileLabels().add(labFast1);
        this.CFloors.get(0).getTileLabels().add(labSpawn1A);
        this.CFloors.get(0).getTileLabels().add(labDoor1A); //2
        
        //Floor 2
        this.CFloors.get(1).getTileLabels().add(labBoss);
        this.CFloors.get(1).getTileLabels().add(labDoor2A); //1
        this.CFloors.get(1).getTileLabels().add(labDoor2B); //2
        
        //Floor 3
        this.CFloors.get(2).getTileLabels().add(labSpawn3A);
        this.CFloors.get(2).getTileLabels().add(labSpawn3B);
        this.CFloors.get(2).getTileLabels().add(labSpawn3C);
        this.CFloors.get(2).getTileLabels().add(labSpawn3D);
        
        this.CFloors.get(2).getTileLabels().add(labSpawn3E);
        this.CFloors.get(2).getTileLabels().add(labSpawn3F);
        this.CFloors.get(2).getTileLabels().add(labSpawn3G);
        this.CFloors.get(2).getTileLabels().add(labSpawn3H);
        
        this.CFloors.get(2).getTileLabels().add(labDoor3A); //8
        
        
        
        //List of Player Sprite JLabels
        this.CFloors.get(0).setPlayerSprite(this.labPlayer1);
        
        this.CFloors.get(1).setPlayerSprite(this.labPlayer2);
        
        this.CFloors.get(2).setPlayerSprite(this.labPlayer3);
    }
    
    /**
     * Checks the Player's current floor before using the appropriate door, areas have individual implementations.
     */
    public void checkDoor(){
        int lvl = CPlayer.getCurrentFloor();
        
        switch(lvl){
            case 0:
                useDoor(0, 1, 2, false); //to Floor 2
                break;
            case 1:
                useDoor(1, -1, 1, true); //go back to Floor 1
                useDoor(1, 1, 2, false); //to Floor 3
                break;
            case 2:
                useDoor(2, -1, 8, true); //go back to Floor 2
        }
        
    } //end of checkDoor()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fmFloor1 = new javax.swing.JFrame();
        labPlayer1 = new javax.swing.JLabel();
        labFast1 = new javax.swing.JLabel();
        labDoor1A = new javax.swing.JLabel();
        labSpawn1A = new javax.swing.JLabel();
        labFloorBack1A = new javax.swing.JLabel();
        labBackground1 = new javax.swing.JLabel();
        fmFloor2 = new javax.swing.JFrame();
        labPlayer2 = new javax.swing.JLabel();
        labDoor2A = new javax.swing.JLabel();
        labDoor2B = new javax.swing.JLabel();
        labBoss = new javax.swing.JLabel();
        labFloorBack2A = new javax.swing.JLabel();
        labFloorBack2B = new javax.swing.JLabel();
        labBackground2 = new javax.swing.JLabel();
        fmFloor3 = new javax.swing.JFrame();
        labPlayer3 = new javax.swing.JLabel();
        labCredit = new javax.swing.JLabel();
        labDoor3A = new javax.swing.JLabel();
        labSpawn3H = new javax.swing.JLabel();
        labSpawn3G = new javax.swing.JLabel();
        labSpawn3F = new javax.swing.JLabel();
        labSpawn3E = new javax.swing.JLabel();
        labSpawn3D = new javax.swing.JLabel();
        labSpawn3C = new javax.swing.JLabel();
        labSpawn3B = new javax.swing.JLabel();
        labSpawn3A = new javax.swing.JLabel();
        labFloorBack3 = new javax.swing.JLabel();
        labBackground3 = new javax.swing.JLabel();
        fmCredits = new javax.swing.JFrame();
        panDivider1 = new javax.swing.JPanel();
        panDivider2 = new javax.swing.JPanel();
        labSpecial = new javax.swing.JLabel();
        labThank = new javax.swing.JLabel();
        labName2 = new javax.swing.JLabel();
        labName1 = new javax.swing.JLabel();
        labTitle4 = new javax.swing.JLabel();
        labTitle3 = new javax.swing.JLabel();
        labTitle2 = new javax.swing.JLabel();
        labTitle1 = new javax.swing.JLabel();
        labBackgroundCredits = new javax.swing.JLabel();

        fmFloor1.setSize(new java.awt.Dimension(840, 640));
        fmFloor1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer1.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer1.setAlignmentY(0.0F);
        labPlayer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer1.setPreferredSize(new java.awt.Dimension(55, 55));
        fmFloor1.getContentPane().add(labPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        labFast1.setBackground(new java.awt.Color(255, 255, 255));
        labFast1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFast1.setForeground(new java.awt.Color(102, 102, 102));
        labFast1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labFast1.setText("F^");
        labFast1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 122, 96), 5));
        labFast1.setMaximumSize(new java.awt.Dimension(50, 50));
        labFast1.setMinimumSize(new java.awt.Dimension(50, 50));
        labFast1.setOpaque(true);
        labFast1.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor1.getContentPane().add(labFast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 60, 60));

        labDoor1A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor1A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor1A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor1A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor1A.setText("D");
        labDoor1A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor1A.setOpaque(true);
        labDoor1A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor1.getContentPane().add(labDoor1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 60, 60));

        labSpawn1A.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn1A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn1A.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn1A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn1A.setText("?");
        labSpawn1A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn1A.setOpaque(true);
        labSpawn1A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor1.getContentPane().add(labSpawn1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 60, 60));

        labFloorBack1A.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack1A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack1A.setForeground(new java.awt.Color(148, 133, 102));
        labFloorBack1A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 133, 102), 5));
        labFloorBack1A.setOpaque(true);
        labFloorBack1A.setPreferredSize(new java.awt.Dimension(375, 225));
        fmFloor1.getContentPane().add(labFloorBack1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 180, 540));

        labBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/EldenThrone.jpg"))); // NOI18N
        labBackground1.setText("jLabel1");
        fmFloor1.getContentPane().add(labBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 970, 640));

        fmFloor2.setSize(new java.awt.Dimension(830, 569));
        fmFloor2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer2.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer2.setAlignmentY(0.0F);
        labPlayer2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer2.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 50, 55));

        labDoor2A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor2A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor2A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor2A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor2A.setText("D");
        labDoor2A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor2A.setOpaque(true);
        labDoor2A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor2.getContentPane().add(labDoor2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 60, 60));

        labDoor2B.setBackground(new java.awt.Color(255, 255, 255));
        labDoor2B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor2B.setForeground(new java.awt.Color(102, 102, 102));
        labDoor2B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor2B.setText("D");
        labDoor2B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor2B.setOpaque(true);
        labDoor2B.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor2.getContentPane().add(labDoor2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 60, 60));

        labBoss.setBackground(new java.awt.Color(255, 255, 255));
        labBoss.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labBoss.setForeground(new java.awt.Color(102, 102, 102));
        labBoss.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labBoss.setText("B");
        labBoss.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(181, 103, 103), 5));
        labBoss.setOpaque(true);
        labBoss.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor2.getContentPane().add(labBoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 60, 60));

        labFloorBack2A.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack2A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack2A.setForeground(new java.awt.Color(148, 133, 102));
        labFloorBack2A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 133, 102), 5));
        labFloorBack2A.setOpaque(true);
        labFloorBack2A.setPreferredSize(new java.awt.Dimension(375, 225));
        fmFloor2.getContentPane().add(labFloorBack2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 300, 420));

        labFloorBack2B.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack2B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack2B.setForeground(new java.awt.Color(148, 133, 102));
        labFloorBack2B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 133, 102), 5));
        labFloorBack2B.setOpaque(true);
        labFloorBack2B.setPreferredSize(new java.awt.Dimension(375, 225));
        fmFloor2.getContentPane().add(labFloorBack2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 420, 300));

        labBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/EldenThrone.jpg"))); // NOI18N
        fmFloor2.getContentPane().add(labBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 970, 640));

        fmFloor3.setSize(new java.awt.Dimension(840, 640));
        fmFloor3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer3.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer3.setAlignmentY(0.0F);
        labPlayer3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer3.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor3.getContentPane().add(labPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 50, 55));

        labCredit.setBackground(new java.awt.Color(255, 255, 255));
        labCredit.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labCredit.setForeground(new java.awt.Color(102, 102, 102));
        labCredit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCredit.setText("C");
        labCredit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(163, 133, 184), 5));
        labCredit.setOpaque(true);
        labCredit.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 60, 60));

        labDoor3A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor3A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor3A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor3A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor3A.setText("D");
        labDoor3A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor3A.setOpaque(true);
        labDoor3A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labDoor3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 60, 60));

        labSpawn3H.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3H.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3H.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3H.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3H.setText("?");
        labSpawn3H.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3H.setOpaque(true);
        labSpawn3H.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3H, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 60, 60));

        labSpawn3G.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3G.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3G.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3G.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3G.setText("?");
        labSpawn3G.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3G.setOpaque(true);
        labSpawn3G.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3G, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 60, 60));

        labSpawn3F.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3F.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3F.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3F.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3F.setText("?");
        labSpawn3F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3F.setOpaque(true);
        labSpawn3F.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3F, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 60, 60));

        labSpawn3E.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3E.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3E.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3E.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3E.setText("?");
        labSpawn3E.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3E.setOpaque(true);
        labSpawn3E.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3E, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 60, 60));

        labSpawn3D.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3D.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3D.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3D.setText("?");
        labSpawn3D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3D.setOpaque(true);
        labSpawn3D.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 60, 60));

        labSpawn3C.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3C.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3C.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3C.setText("?");
        labSpawn3C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3C.setOpaque(true);
        labSpawn3C.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3C, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 60, 60));

        labSpawn3B.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3B.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3B.setText("?");
        labSpawn3B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3B.setOpaque(true);
        labSpawn3B.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 60, 60));

        labSpawn3A.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3A.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3A.setText("?");
        labSpawn3A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3A.setOpaque(true);
        labSpawn3A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 60, 60));

        labFloorBack3.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack3.setForeground(new java.awt.Color(148, 133, 102));
        labFloorBack3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 133, 102), 5));
        labFloorBack3.setOpaque(true);
        labFloorBack3.setPreferredSize(new java.awt.Dimension(375, 225));
        fmFloor3.getContentPane().add(labFloorBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 180, 540));

        labBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/EldenThrone.jpg"))); // NOI18N
        fmFloor3.getContentPane().add(labBackground3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 970, 640));

        fmCredits.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panDivider1Layout = new javax.swing.GroupLayout(panDivider1);
        panDivider1.setLayout(panDivider1Layout);
        panDivider1Layout.setHorizontalGroup(
            panDivider1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        panDivider1Layout.setVerticalGroup(
            panDivider1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        fmCredits.getContentPane().add(panDivider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 380, 10));

        javax.swing.GroupLayout panDivider2Layout = new javax.swing.GroupLayout(panDivider2);
        panDivider2.setLayout(panDivider2Layout);
        panDivider2Layout.setHorizontalGroup(
            panDivider2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        panDivider2Layout.setVerticalGroup(
            panDivider2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        fmCredits.getContentPane().add(panDivider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 380, 10));

        labSpecial.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        labSpecial.setForeground(new java.awt.Color(59, 67, 84));
        labSpecial.setText("SPECIAL THANKS");
        fmCredits.getContentPane().add(labSpecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        labThank.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        labThank.setForeground(new java.awt.Color(59, 67, 84));
        labThank.setText("THANK YOU FOR PLAYING!");
        fmCredits.getContentPane().add(labThank, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        labName2.setFont(new java.awt.Font("ROG Fonts", 0, 18)); // NOI18N
        labName2.setForeground(new java.awt.Color(59, 67, 84));
        labName2.setText("BALBASTRO, LIANNE MAXENE");
        fmCredits.getContentPane().add(labName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        labName1.setFont(new java.awt.Font("ROG Fonts", 0, 18)); // NOI18N
        labName1.setForeground(new java.awt.Color(59, 67, 84));
        labName1.setText("ANG, JEREMIAH MAXWELL");
        fmCredits.getContentPane().add(labName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        labTitle4.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        labTitle4.setForeground(new java.awt.Color(59, 67, 84));
        labTitle4.setText("DEVELOPERS");
        fmCredits.getContentPane().add(labTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        labTitle3.setFont(new java.awt.Font("Serif", 1, 78)); // NOI18N
        labTitle3.setForeground(new java.awt.Color(59, 67, 84));
        labTitle3.setText("E");
        fmCredits.getContentPane().add(labTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 70, 140));

        labTitle2.setFont(new java.awt.Font("Serif", 1, 58)); // NOI18N
        labTitle2.setForeground(new java.awt.Color(59, 67, 84));
        labTitle2.setText("LDEN ROGU");
        fmCredits.getContentPane().add(labTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        labTitle1.setFont(new java.awt.Font("Serif", 1, 78)); // NOI18N
        labTitle1.setForeground(new java.awt.Color(59, 67, 84));
        labTitle1.setText("E");
        fmCredits.getContentPane().add(labTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 70, 140));

        labBackgroundCredits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Credits.jpg"))); // NOI18N
        fmCredits.getContentPane().add(labBackgroundCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 590));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(830, 569));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.dispose();
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame fmCredits;
    private javax.swing.JFrame fmFloor1;
    private javax.swing.JFrame fmFloor2;
    private javax.swing.JFrame fmFloor3;
    private javax.swing.JLabel labBackground1;
    private javax.swing.JLabel labBackground2;
    private javax.swing.JLabel labBackground3;
    private javax.swing.JLabel labBackgroundCredits;
    private javax.swing.JLabel labBoss;
    private javax.swing.JLabel labCredit;
    private javax.swing.JLabel labDoor1A;
    private javax.swing.JLabel labDoor2A;
    private javax.swing.JLabel labDoor2B;
    private javax.swing.JLabel labDoor3A;
    private javax.swing.JLabel labFast1;
    private javax.swing.JLabel labFloorBack1A;
    private javax.swing.JLabel labFloorBack2A;
    private javax.swing.JLabel labFloorBack2B;
    private javax.swing.JLabel labFloorBack3;
    private javax.swing.JLabel labName1;
    private javax.swing.JLabel labName2;
    private javax.swing.JLabel labPlayer1;
    private javax.swing.JLabel labPlayer2;
    private javax.swing.JLabel labPlayer3;
    private javax.swing.JLabel labSpawn1A;
    private javax.swing.JLabel labSpawn3A;
    private javax.swing.JLabel labSpawn3B;
    private javax.swing.JLabel labSpawn3C;
    private javax.swing.JLabel labSpawn3D;
    private javax.swing.JLabel labSpawn3E;
    private javax.swing.JLabel labSpawn3F;
    private javax.swing.JLabel labSpawn3G;
    private javax.swing.JLabel labSpawn3H;
    private javax.swing.JLabel labSpecial;
    private javax.swing.JLabel labThank;
    private javax.swing.JLabel labTitle1;
    private javax.swing.JLabel labTitle2;
    private javax.swing.JLabel labTitle3;
    private javax.swing.JLabel labTitle4;
    private javax.swing.JPanel panDivider1;
    private javax.swing.JPanel panDivider2;
    // End of variables declaration//GEN-END:variables
}
