/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mco2_ang_balbastro;

/**
 * Displays the screen where an area could be selected.
 * 
 * @author ANG, JEREMIAH MAXWELL
 * @author BALBASTRO, LIANNE MAXENE
 * @version 1.0
 */
public class GameLobby extends javax.swing.JFrame {
    /**
     * The Player that chooses whether to fast travel or level up.
     */
    private Player CPlayer;
    
    /**
     * Class constructor requiring a Player to be passed to this GameLobby.
     * Creates new form GameLobby
     * @param CPlayer
     */
    GameLobby(Player CPlayer) {
        this.CPlayer = CPlayer;
        initComponents();
        
    }

    /**
     * Class constructor.
     * Throws exception.
     */
    GameLobby() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    /**
     * Displays the Player's name, job class, and statistics.
     * @param CPlayer 
     */
    public void displayDetails(Player CPlayer){
        txtCharDetails.setContentType("text/html"); // Allows HTML content
        String htmlContent = "<html>" +
                        "<body>" +
                        "<div style='text-align: center;'><b>-- Current Character Info --</b></div><br/>" +
                        "<div><b>Name:</b> " + CPlayer.getName() + "</div>" +
                        "<div><b>Job Class:</b> " + CPlayer.getJobClass() + "</div>" +
                        "<div><b>Level:</b> " + CPlayer.getPlayerLevel() + "</div>" +
                        "<div><b>Runes:</b> " + CPlayer.getRunes() + "</div>" +
                                                
                        "<div><b>HP:</b> " + CPlayer.getHealth() + "</div>" +
                        "<div><b>DEXTERITY:</b> " + CPlayer.getDexterity() + "</div>" +
                        "<div><b>INTELLIGENCE:</b> " + CPlayer.getIntelligence() + "</div>" +
                        "<div><b>ENDURANCE:</b> " + CPlayer.getEndurance() + "</div>" +
                        "<div><b>STRENGTH:</b> " + CPlayer.getStrength() + "</div>" +
                        "<div><b>FAITH:</b> " + CPlayer.getFaith() + "</div>" +
                        "</body></html>";
        txtCharDetails.setText(htmlContent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneDetails = new javax.swing.JScrollPane();
        txtCharDetails = new javax.swing.JTextPane();
        labGame = new javax.swing.JLabel();
        labLobby = new javax.swing.JLabel();
        labG = new javax.swing.JLabel();
        labY = new javax.swing.JLabel();
        panelUnderline = new javax.swing.JPanel();
        bFastTrav = new javax.swing.JButton();
        bLevelUp = new javax.swing.JButton();
        bInventory = new javax.swing.JButton();
        bShop = new javax.swing.JButton();
        bQuit = new javax.swing.JButton();
        labBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCharDetails.setEditable(false);
        txtCharDetails.setBackground(new java.awt.Color(204, 204, 255));
        txtCharDetails.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        paneDetails.setViewportView(txtCharDetails);

        getContentPane().add(paneDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 230, 230));

        labGame.setFont(new java.awt.Font("Serif", 1, 58)); // NOI18N
        labGame.setForeground(new java.awt.Color(60, 62, 106));
        labGame.setText("AME");
        getContentPane().add(labGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        labLobby.setFont(new java.awt.Font("Serif", 1, 58)); // NOI18N
        labLobby.setForeground(new java.awt.Color(60, 62, 106));
        labLobby.setText("LOBB");
        getContentPane().add(labLobby, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        labG.setFont(new java.awt.Font("Serif", 1, 78)); // NOI18N
        labG.setForeground(new java.awt.Color(60, 62, 106));
        labG.setText("G");
        getContentPane().add(labG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        labY.setFont(new java.awt.Font("Serif", 1, 78)); // NOI18N
        labY.setForeground(new java.awt.Color(60, 62, 106));
        labY.setText("Y");
        labY.setToolTipText("");
        labY.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(labY, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));

        panelUnderline.setBackground(new java.awt.Color(60, 62, 106));

        javax.swing.GroupLayout panelUnderlineLayout = new javax.swing.GroupLayout(panelUnderline);
        panelUnderline.setLayout(panelUnderlineLayout);
        panelUnderlineLayout.setHorizontalGroup(
            panelUnderlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        panelUnderlineLayout.setVerticalGroup(
            panelUnderlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(panelUnderline, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 330, -1));

        bFastTrav.setBackground(new java.awt.Color(60, 62, 106));
        bFastTrav.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        bFastTrav.setForeground(new java.awt.Color(255, 255, 255));
        bFastTrav.setText("FAST TRAVEL");
        bFastTrav.setBorderPainted(false);
        bFastTrav.setFocusable(false);
        bFastTrav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFastTravActionPerformed(evt);
            }
        });
        getContentPane().add(bFastTrav, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 210, 30));

        bLevelUp.setBackground(new java.awt.Color(60, 62, 106));
        bLevelUp.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        bLevelUp.setForeground(new java.awt.Color(255, 255, 255));
        bLevelUp.setText("LEVEL UP");
        bLevelUp.setBorderPainted(false);
        bLevelUp.setFocusable(false);
        bLevelUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLevelUpActionPerformed(evt);
            }
        });
        getContentPane().add(bLevelUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 210, 30));

        bInventory.setBackground(new java.awt.Color(60, 62, 106));
        bInventory.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        bInventory.setForeground(new java.awt.Color(255, 255, 255));
        bInventory.setText("INVENTORY");
        bInventory.setBorderPainted(false);
        bInventory.setFocusable(false);
        bInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInventoryActionPerformed(evt);
            }
        });
        getContentPane().add(bInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 210, 30));

        bShop.setBackground(new java.awt.Color(60, 62, 106));
        bShop.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        bShop.setForeground(new java.awt.Color(255, 255, 255));
        bShop.setText("SHOP");
        bShop.setBorderPainted(false);
        bShop.setFocusable(false);
        bShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShopActionPerformed(evt);
            }
        });
        getContentPane().add(bShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 210, 30));

        bQuit.setBackground(new java.awt.Color(60, 62, 106));
        bQuit.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        bQuit.setForeground(new java.awt.Color(255, 255, 255));
        bQuit.setText("QUIT GAME");
        bQuit.setBorderPainted(false);
        bQuit.setFocusable(false);
        bQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitActionPerformed(evt);
            }
        });
        getContentPane().add(bQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 210, 30));

        labBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/GameLobby.jpg"))); // NOI18N
        getContentPane().add(labBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLevelUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLevelUpActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new LevelUp(CPlayer).setVisible(true);
            this.dispose();
        });
        
    }//GEN-LAST:event_bLevelUpActionPerformed

    private void bFastTravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFastTravActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new FastTravel(CPlayer).setVisible(true);
            this.dispose();
        });
    }//GEN-LAST:event_bFastTravActionPerformed

    private void bQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new TitleMenu().setVisible(true);
            this.dispose();
        });
    }//GEN-LAST:event_bQuitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Shows Player details once window is opened
        displayDetails(CPlayer);
    }//GEN-LAST:event_formWindowOpened

    private void bInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInventoryActionPerformed
            java.awt.EventQueue.invokeLater(() -> {
            new Inventory(CPlayer).setVisible(true);
            this.dispose();
        });
    }//GEN-LAST:event_bInventoryActionPerformed

    private void bShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShopActionPerformed
            java.awt.EventQueue.invokeLater(() -> {
            new Shop(CPlayer).setVisible(true);
            this.dispose();
        });
    }//GEN-LAST:event_bShopActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFastTrav;
    private javax.swing.JButton bInventory;
    private javax.swing.JButton bLevelUp;
    private javax.swing.JButton bQuit;
    private javax.swing.JButton bShop;
    private javax.swing.JLabel labBackground;
    private javax.swing.JLabel labG;
    private javax.swing.JLabel labGame;
    private javax.swing.JLabel labLobby;
    private javax.swing.JLabel labY;
    private javax.swing.JScrollPane paneDetails;
    private javax.swing.JPanel panelUnderline;
    private javax.swing.JTextPane txtCharDetails;
    // End of variables declaration//GEN-END:variables
}
