/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mco2_ang_balbastro;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 * Displays the Raya Lucaria area.
 * 
 * @author ANG, JEREMIAH MAXWELL
 * @author BALBASTRO, LIANNE MAXENE
 * @version 2.0
 */
public class RayaLucaria extends Area {

    /**
     * Creates new form RayaLucaria
     */
    public RayaLucaria(Player CPlayer) {
        super(5, CPlayer, 2, "Raya Lucaria");
        initComponents();
        
        createLabelList();
        this.fmFloor1.setVisible(true);
        
        
        //from the Area parent
        //int parameters: floor num, # of fast, # of spawn, # of boss, # of door
        generateFloor(0, 1, 2, 0, 1);
        generateFloor(1, 0, 3, 0, 2);
        generateFloor(2, 0, 2, 0, 3);
        generateFloor(3, 0, 4, 0, 1);
        generateFloor(4, 1, 7, 1, 1);
        
        
        associateLabels(this.nFloorCount); //from the Area parent
        initializeKeyListener(); 
        
        this.fmFloor1.setFocusable(true);
        this.fmFloor1.requestFocusInWindow();
    }
    
    private void createLabelList(){
        //List of Floor JFrames
        this.CFloors.get(0).setFloorFrames(fmFloor1);
        this.CFloors.get(0).getFloorBack().add(labFloorBack1A);
        
        this.CFloors.get(1).setFloorFrames(fmFloor2);
        this.CFloors.get(1).getFloorBack().add(labFloorBack2A);
        
        this.CFloors.get(2).setFloorFrames(fmFloor3);
        this.CFloors.get(2).getFloorBack().add(labFloorBack3A);
        this.CFloors.get(2).getFloorBack().add(labFloorBack3B);
        
        this.CFloors.get(3).setFloorFrames(fmFloor4);
        this.CFloors.get(3).getFloorBack().add(labFloorBack4A);
        
        this.CFloors.get(4).setFloorFrames(fmFloor5);
        this.CFloors.get(4).getFloorBack().add(labFloorBack5A);
        this.CFloors.get(4).getFloorBack().add(labFloorBack5B);
        
        addScreenDetails(this.CFloors);
        
        //List of Tile JLabels
        
        //Floor 1
        this.CFloors.get(0).getTileLabels().add(labFast1);
        this.CFloors.get(0).getTileLabels().add(labSpawn1A);
        this.CFloors.get(0).getTileLabels().add(labSpawn1B);
        
        this.CFloors.get(0).getTileLabels().add(labDoor1A); //3
        
        //Floor 2
        this.CFloors.get(1).getTileLabels().add(labSpawn2A);
        this.CFloors.get(1).getTileLabels().add(labSpawn2B);
        this.CFloors.get(1).getTileLabels().add(labSpawn2C);

        this.CFloors.get(1).getTileLabels().add(labDoor2A); //3
        this.CFloors.get(1).getTileLabels().add(labDoor2B); //4
        
        //Floor 3
        this.CFloors.get(2).getTileLabels().add(labSpawn3A);
        this.CFloors.get(2).getTileLabels().add(labSpawn3B);

        this.CFloors.get(2).getTileLabels().add(labDoor3A); //2
        this.CFloors.get(2).getTileLabels().add(labDoor3B); //3
        this.CFloors.get(2).getTileLabels().add(labDoor3C); //4
        
        //Floor 4
        this.CFloors.get(3).getTileLabels().add(labSpawn4A);
        this.CFloors.get(3).getTileLabels().add(labSpawn4B);
        this.CFloors.get(3).getTileLabels().add(labSpawn4C);
        this.CFloors.get(3).getTileLabels().add(labSpawn4D);

        this.CFloors.get(3).getTileLabels().add(labDoor4A); //4
        
        //Floor 5
        this.CFloors.get(4).getTileLabels().add(labFast5);
        this.CFloors.get(4).getTileLabels().add(labSpawn5A);
        this.CFloors.get(4).getTileLabels().add(labSpawn5B);
        this.CFloors.get(4).getTileLabels().add(labSpawn5C);
        this.CFloors.get(4).getTileLabels().add(labSpawn5D);
        this.CFloors.get(4).getTileLabels().add(labSpawn5E);
        this.CFloors.get(4).getTileLabels().add(labSpawn5F);
        this.CFloors.get(4).getTileLabels().add(labSpawn5G);
        this.CFloors.get(4).getTileLabels().add(labBoss);

        this.CFloors.get(4).getTileLabels().add(labDoor5A); //9
        
        
        //List of Player Sprite JLabels
        this.CFloors.get(0).setPlayerSprite(this.labPlayer1);
        
        this.CFloors.get(1).setPlayerSprite(this.labPlayer2);
        
        this.CFloors.get(2).setPlayerSprite(this.labPlayer3);
        
        this.CFloors.get(3).setPlayerSprite(this.labPlayer4);
        
        this.CFloors.get(4).setPlayerSprite(this.labPlayer5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fmFloor1 = new javax.swing.JFrame();
        labPlayer1 = new javax.swing.JLabel();
        labFast1 = new javax.swing.JLabel();
        labDoor1A = new javax.swing.JLabel();
        labSpawn1A = new javax.swing.JLabel();
        labSpawn1B = new javax.swing.JLabel();
        labFloorBack1A = new javax.swing.JLabel();
        labBackground1 = new javax.swing.JLabel();
        fmFloor2 = new javax.swing.JFrame();
        labPlayer2 = new javax.swing.JLabel();
        labDoor2B = new javax.swing.JLabel();
        labDoor2A = new javax.swing.JLabel();
        labSpawn2A = new javax.swing.JLabel();
        labSpawn2C = new javax.swing.JLabel();
        labSpawn2B = new javax.swing.JLabel();
        labFloorBack2A = new javax.swing.JLabel();
        labBackground2 = new javax.swing.JLabel();
        fmFloor3 = new javax.swing.JFrame();
        labPlayer3 = new javax.swing.JLabel();
        labDoor3C = new javax.swing.JLabel();
        labDoor3B = new javax.swing.JLabel();
        labDoor3A = new javax.swing.JLabel();
        labSpawn3A = new javax.swing.JLabel();
        labSpawn3B = new javax.swing.JLabel();
        labFloorBack3B = new javax.swing.JLabel();
        labFloorBack3A = new javax.swing.JLabel();
        labBackground3 = new javax.swing.JLabel();
        fmFloor4 = new javax.swing.JFrame();
        labPlayer4 = new javax.swing.JLabel();
        labDoor4A = new javax.swing.JLabel();
        labSpawn4A = new javax.swing.JLabel();
        labSpawn4B = new javax.swing.JLabel();
        labSpawn4D = new javax.swing.JLabel();
        labSpawn4C = new javax.swing.JLabel();
        labFloorBack4A = new javax.swing.JLabel();
        labBackground4 = new javax.swing.JLabel();
        fmFloor5 = new javax.swing.JFrame();
        labPlayer5 = new javax.swing.JLabel();
        labBoss = new javax.swing.JLabel();
        labFast5 = new javax.swing.JLabel();
        labDoor5A = new javax.swing.JLabel();
        labSpawn5D = new javax.swing.JLabel();
        labSpawn5G = new javax.swing.JLabel();
        labSpawn5E = new javax.swing.JLabel();
        labSpawn5B = new javax.swing.JLabel();
        labSpawn5A = new javax.swing.JLabel();
        labSpawn5F = new javax.swing.JLabel();
        labSpawn5C = new javax.swing.JLabel();
        labFloorBack5A = new javax.swing.JLabel();
        labFloorBack5B = new javax.swing.JLabel();
        labBackground5 = new javax.swing.JLabel();

        fmFloor1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        fmFloor1.setForeground(new java.awt.Color(0, 0, 0));
        fmFloor1.setMinimumSize(new java.awt.Dimension(830, 569));
        fmFloor1.setSize(new java.awt.Dimension(830, 569));
        fmFloor1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer1.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer1.setAlignmentY(0.0F);
        labPlayer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer1.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor1.getContentPane().add(labPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 50, 60));

        labFast1.setBackground(new java.awt.Color(255, 255, 255));
        labFast1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFast1.setForeground(new java.awt.Color(102, 102, 102));
        labFast1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labFast1.setText("F^");
        labFast1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 122, 96), 5));
        labFast1.setMaximumSize(new java.awt.Dimension(50, 50));
        labFast1.setMinimumSize(new java.awt.Dimension(50, 50));
        labFast1.setOpaque(true);
        labFast1.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor1.getContentPane().add(labFast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 60, 60));

        labDoor1A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor1A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor1A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor1A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor1A.setText("D");
        labDoor1A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor1A.setOpaque(true);
        labDoor1A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor1.getContentPane().add(labDoor1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 60, 60));

        labSpawn1A.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn1A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn1A.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn1A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn1A.setText("?");
        labSpawn1A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn1A.setOpaque(true);
        labSpawn1A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor1.getContentPane().add(labSpawn1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 60, 60));

        labSpawn1B.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn1B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn1B.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn1B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn1B.setText("?");
        labSpawn1B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn1B.setOpaque(true);
        labSpawn1B.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor1.getContentPane().add(labSpawn1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 60, 60));

        labFloorBack1A.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack1A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack1A.setForeground(new java.awt.Color(102, 102, 102));
        labFloorBack1A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 150, 153), 5));
        labFloorBack1A.setOpaque(true);
        labFloorBack1A.setPreferredSize(new java.awt.Dimension(375, 225));
        fmFloor1.getContentPane().add(labFloorBack1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 300, 300));

        labBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/RayaLucaria.jpg"))); // NOI18N
        fmFloor1.getContentPane().add(labBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 570));

        fmFloor2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        fmFloor2.setForeground(new java.awt.Color(0, 0, 0));
        fmFloor2.setMinimumSize(new java.awt.Dimension(830, 569));
        fmFloor2.setSize(new java.awt.Dimension(830, 569));
        fmFloor2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer2.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer2.setAlignmentY(0.0F);
        labPlayer2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer2.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 50, 60));

        labDoor2B.setBackground(new java.awt.Color(255, 255, 255));
        labDoor2B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor2B.setForeground(new java.awt.Color(102, 102, 102));
        labDoor2B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor2B.setText("D");
        labDoor2B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor2B.setOpaque(true);
        labDoor2B.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor2.getContentPane().add(labDoor2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 60, 60));

        labDoor2A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor2A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor2A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor2A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor2A.setText("D");
        labDoor2A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor2A.setOpaque(true);
        labDoor2A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor2.getContentPane().add(labDoor2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 60, 60));

        labSpawn2A.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2A.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn2A.setText("?");
        labSpawn2A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2A.setOpaque(true);
        labSpawn2A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor2.getContentPane().add(labSpawn2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 60, 60));

        labSpawn2C.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2C.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2C.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn2C.setText("?");
        labSpawn2C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2C.setOpaque(true);
        labSpawn2C.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor2.getContentPane().add(labSpawn2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 60, 60));

        labSpawn2B.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2B.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn2B.setText("?");
        labSpawn2B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2B.setOpaque(true);
        labSpawn2B.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor2.getContentPane().add(labSpawn2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 60, 60));

        labFloorBack2A.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack2A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack2A.setForeground(new java.awt.Color(102, 102, 102));
        labFloorBack2A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 150, 153), 5));
        labFloorBack2A.setOpaque(true);
        labFloorBack2A.setPreferredSize(new java.awt.Dimension(180, 420));
        fmFloor2.getContentPane().add(labFloorBack2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, 420));

        labBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/RayaLucaria.jpg"))); // NOI18N
        fmFloor2.getContentPane().add(labBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, 920, 740));

        fmFloor3.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        fmFloor3.setForeground(new java.awt.Color(0, 0, 0));
        fmFloor3.setMinimumSize(new java.awt.Dimension(830, 569));
        fmFloor3.setSize(new java.awt.Dimension(830, 569));
        fmFloor3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer3.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer3.setAlignmentY(0.0F);
        labPlayer3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer3.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor3.getContentPane().add(labPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, 60));

        labDoor3C.setBackground(new java.awt.Color(255, 255, 255));
        labDoor3C.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor3C.setForeground(new java.awt.Color(102, 102, 102));
        labDoor3C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor3C.setText("D");
        labDoor3C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor3C.setOpaque(true);
        labDoor3C.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labDoor3C, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 60, 60));

        labDoor3B.setBackground(new java.awt.Color(255, 255, 255));
        labDoor3B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor3B.setForeground(new java.awt.Color(102, 102, 102));
        labDoor3B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor3B.setText("D");
        labDoor3B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor3B.setOpaque(true);
        labDoor3B.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labDoor3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 60, 60));

        labDoor3A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor3A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor3A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor3A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor3A.setText("D");
        labDoor3A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor3A.setOpaque(true);
        labDoor3A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labDoor3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 60, 60));

        labSpawn3A.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3A.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3A.setText("?");
        labSpawn3A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3A.setOpaque(true);
        labSpawn3A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 60, 60));

        labSpawn3B.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn3B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn3B.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn3B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn3B.setText("?");
        labSpawn3B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn3B.setOpaque(true);
        labSpawn3B.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labSpawn3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 60, 60));

        labFloorBack3B.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack3B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack3B.setForeground(new java.awt.Color(204, 204, 204));
        labFloorBack3B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 150, 153), 5));
        labFloorBack3B.setOpaque(true);
        labFloorBack3B.setPreferredSize(new java.awt.Dimension(375, 225));
        fmFloor3.getContentPane().add(labFloorBack3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 180, 420));

        labFloorBack3A.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack3A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack3A.setForeground(new java.awt.Color(102, 102, 102));
        labFloorBack3A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(56, 89, 99), 5));
        labFloorBack3A.setOpaque(true);
        labFloorBack3A.setPreferredSize(new java.awt.Dimension(375, 225));
        fmFloor3.getContentPane().add(labFloorBack3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 300, 180));

        labBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/RayaLucaria.jpg"))); // NOI18N
        fmFloor3.getContentPane().add(labBackground3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        fmFloor4.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        fmFloor4.setForeground(new java.awt.Color(0, 0, 0));
        fmFloor4.setMinimumSize(new java.awt.Dimension(830, 569));
        fmFloor4.setSize(new java.awt.Dimension(830, 569));
        fmFloor4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer4.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer4.setAlignmentY(0.0F);
        labPlayer4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer4.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor4.getContentPane().add(labPlayer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 50, 60));

        labDoor4A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor4A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor4A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor4A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor4A.setText("D");
        labDoor4A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor4A.setOpaque(true);
        labDoor4A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor4.getContentPane().add(labDoor4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 60, 60));

        labSpawn4A.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn4A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn4A.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn4A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn4A.setText("?");
        labSpawn4A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn4A.setOpaque(true);
        labSpawn4A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor4.getContentPane().add(labSpawn4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 60, 60));

        labSpawn4B.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn4B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn4B.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn4B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn4B.setText("?");
        labSpawn4B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn4B.setOpaque(true);
        labSpawn4B.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor4.getContentPane().add(labSpawn4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 60, 60));

        labSpawn4D.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn4D.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn4D.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn4D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn4D.setText("?");
        labSpawn4D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn4D.setOpaque(true);
        labSpawn4D.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor4.getContentPane().add(labSpawn4D, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 60, 60));

        labSpawn4C.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn4C.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn4C.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn4C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn4C.setText("?");
        labSpawn4C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn4C.setOpaque(true);
        labSpawn4C.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor4.getContentPane().add(labSpawn4C, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 60, 60));

        labFloorBack4A.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack4A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack4A.setForeground(new java.awt.Color(102, 102, 102));
        labFloorBack4A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 150, 153), 5));
        labFloorBack4A.setOpaque(true);
        labFloorBack4A.setPreferredSize(new java.awt.Dimension(360, 180));
        fmFloor4.getContentPane().add(labFloorBack4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        labBackground4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/RayaLucaria.jpg"))); // NOI18N
        fmFloor4.getContentPane().add(labBackground4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, 920, 740));

        fmFloor5.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        fmFloor5.setForeground(new java.awt.Color(0, 0, 0));
        fmFloor5.setMinimumSize(new java.awt.Dimension(830, 569));
        fmFloor5.setSize(new java.awt.Dimension(830, 569));
        fmFloor5.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer5.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer5.setAlignmentY(0.0F);
        labPlayer5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer5.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor5.getContentPane().add(labPlayer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 50, 60));

        labBoss.setBackground(new java.awt.Color(255, 255, 255));
        labBoss.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labBoss.setForeground(new java.awt.Color(102, 102, 102));
        labBoss.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labBoss.setText("B");
        labBoss.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(181, 103, 103), 5));
        labBoss.setOpaque(true);
        labBoss.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labBoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 60, 60));

        labFast5.setBackground(new java.awt.Color(255, 255, 255));
        labFast5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFast5.setForeground(new java.awt.Color(102, 102, 102));
        labFast5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labFast5.setText("F^");
        labFast5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 122, 96), 5));
        labFast5.setMaximumSize(new java.awt.Dimension(50, 50));
        labFast5.setMinimumSize(new java.awt.Dimension(50, 50));
        labFast5.setOpaque(true);
        labFast5.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labFast5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 60, 60));

        labDoor5A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor5A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor5A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor5A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor5A.setText("D");
        labDoor5A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor5A.setOpaque(true);
        labDoor5A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labDoor5A, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 60, 60));

        labSpawn5D.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn5D.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn5D.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn5D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn5D.setText("?");
        labSpawn5D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn5D.setOpaque(true);
        labSpawn5D.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labSpawn5D, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 60, 60));

        labSpawn5G.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn5G.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn5G.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn5G.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn5G.setText("?");
        labSpawn5G.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn5G.setOpaque(true);
        labSpawn5G.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labSpawn5G, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 60, 60));

        labSpawn5E.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn5E.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn5E.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn5E.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn5E.setText("?");
        labSpawn5E.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn5E.setOpaque(true);
        labSpawn5E.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labSpawn5E, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 60, 60));

        labSpawn5B.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn5B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn5B.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn5B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn5B.setText("?");
        labSpawn5B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn5B.setOpaque(true);
        labSpawn5B.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labSpawn5B, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 60, 60));

        labSpawn5A.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn5A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn5A.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn5A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn5A.setText("?");
        labSpawn5A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn5A.setOpaque(true);
        labSpawn5A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labSpawn5A, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 60, 60));

        labSpawn5F.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn5F.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn5F.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn5F.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn5F.setText("?");
        labSpawn5F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn5F.setOpaque(true);
        labSpawn5F.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labSpawn5F, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 60, 60));

        labSpawn5C.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn5C.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn5C.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn5C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn5C.setText("?");
        labSpawn5C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn5C.setOpaque(true);
        labSpawn5C.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor5.getContentPane().add(labSpawn5C, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 60, 60));

        labFloorBack5A.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack5A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack5A.setForeground(new java.awt.Color(204, 204, 204));
        labFloorBack5A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 150, 153), 5));
        labFloorBack5A.setOpaque(true);
        labFloorBack5A.setPreferredSize(new java.awt.Dimension(420, 420));
        fmFloor5.getContentPane().add(labFloorBack5A, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        labFloorBack5B.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack5B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack5B.setForeground(new java.awt.Color(102, 102, 102));
        labFloorBack5B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 150, 153), 5));
        labFloorBack5B.setOpaque(true);
        labFloorBack5B.setPreferredSize(new java.awt.Dimension(180, 60));
        fmFloor5.getContentPane().add(labFloorBack5B, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        labBackground5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/RayaLucaria.jpg"))); // NOI18N
        fmFloor5.getContentPane().add(labBackground5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.dispose();
    }//GEN-LAST:event_formWindowOpened

    /**
     * Checks the Player's current floor before using the appropriate door, areas have individual implementations.
     */
    public void checkDoor(){
        int lvl = CPlayer.getCurrentFloor();
        
        switch(lvl){
            case 0:
                useDoor(0, 1, 3, false); //to Floor 2
                break;
            case 1:
                useDoor(1, -1, 3, true); //go back to Floor 1
                useDoor(1, 1, 4, false); //to Floor 3
                break;
            case 2:
                useDoor(2, -1, 2, true); //go back to Floor 2
                useDoor(2, 1, 3, false); //to Floor 4
                useDoor(2, 2, 4, false); //to Floor 5
                break;
            case 3:
                useDoor(3, -1, 4, true); //go back to Floor 3
                break;
            case 4:
                useDoor(4, -2, 9, true); //go back to Floor 3
                break;
        }
        
    } //end of checkDoor()


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame fmFloor1;
    private javax.swing.JFrame fmFloor2;
    private javax.swing.JFrame fmFloor3;
    private javax.swing.JFrame fmFloor4;
    private javax.swing.JFrame fmFloor5;
    private javax.swing.JLabel labBackground1;
    private javax.swing.JLabel labBackground2;
    private javax.swing.JLabel labBackground3;
    private javax.swing.JLabel labBackground4;
    private javax.swing.JLabel labBackground5;
    private javax.swing.JLabel labBoss;
    private javax.swing.JLabel labDoor1A;
    private javax.swing.JLabel labDoor2A;
    private javax.swing.JLabel labDoor2B;
    private javax.swing.JLabel labDoor3A;
    private javax.swing.JLabel labDoor3B;
    private javax.swing.JLabel labDoor3C;
    private javax.swing.JLabel labDoor4A;
    private javax.swing.JLabel labDoor5A;
    private javax.swing.JLabel labFast1;
    private javax.swing.JLabel labFast5;
    private javax.swing.JLabel labFloorBack1A;
    private javax.swing.JLabel labFloorBack2A;
    private javax.swing.JLabel labFloorBack3A;
    private javax.swing.JLabel labFloorBack3B;
    private javax.swing.JLabel labFloorBack4A;
    private javax.swing.JLabel labFloorBack5A;
    private javax.swing.JLabel labFloorBack5B;
    private javax.swing.JLabel labPlayer1;
    private javax.swing.JLabel labPlayer2;
    private javax.swing.JLabel labPlayer3;
    private javax.swing.JLabel labPlayer4;
    private javax.swing.JLabel labPlayer5;
    private javax.swing.JLabel labSpawn1A;
    private javax.swing.JLabel labSpawn1B;
    private javax.swing.JLabel labSpawn2A;
    private javax.swing.JLabel labSpawn2B;
    private javax.swing.JLabel labSpawn2C;
    private javax.swing.JLabel labSpawn3A;
    private javax.swing.JLabel labSpawn3B;
    private javax.swing.JLabel labSpawn4A;
    private javax.swing.JLabel labSpawn4B;
    private javax.swing.JLabel labSpawn4C;
    private javax.swing.JLabel labSpawn4D;
    private javax.swing.JLabel labSpawn5A;
    private javax.swing.JLabel labSpawn5B;
    private javax.swing.JLabel labSpawn5C;
    private javax.swing.JLabel labSpawn5D;
    private javax.swing.JLabel labSpawn5E;
    private javax.swing.JLabel labSpawn5F;
    private javax.swing.JLabel labSpawn5G;
    // End of variables declaration//GEN-END:variables
}
