/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mco2_ang_balbastro;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Lianne
 */
public class Shop extends javax.swing.JFrame {
    
    private Player CPlayer;
    private int selectedWeaponIndex = -1;
    private ArrayList<Weapon> weapons;
    
    public Shop(Player player) {
        initComponents();
        this.CPlayer = player;
        this.weapons = Weapon.initializeWeapons();
        // Assuming a method to update the rune count display exists
        updateRuneCountDisplay();
        assignWeaponActions();
    }
    
    private void updateRuneCountDisplay() {
        txtRuneCount.setText("Runes: " + CPlayer.getRunes());
    }
    
    private void selectWeapon(int index) {
        selectedWeaponIndex = index;
        Weapon weapon = weapons.get(index);
        InfoStat.setText(weapon.getDetails(weapons));
    }
        
    private void assignWeaponActions() {
        ShortSword.addActionListener(evt -> selectWeapon(0));
        RogiersRapier.addActionListener(evt -> selectWeapon(1));
        CodedSword.addActionListener(evt -> selectWeapon(2));
        SwordofNightandFlame.addActionListener(evt -> selectWeapon(3));
        Uchigatana.addActionListener(evt -> selectWeapon(4));
        Moonveil.addActionListener(evt -> selectWeapon(5));
        RiversofBlood.addActionListener(evt -> selectWeapon(6));
        HandofMalenia.addActionListener(evt -> selectWeapon(7));
        Whip.addActionListener(evt -> selectWeapon(8));
        Urumi.addActionListener(evt -> selectWeapon(9));
        ThornedWhip.addActionListener(evt -> selectWeapon(10));
        HoslowsPetalWhip.addActionListener(evt -> selectWeapon(11));
        Claymore.addActionListener(evt -> selectWeapon(12));
        StarscourgeGreatsword.addActionListener(evt -> selectWeapon(13));
        InseparableSword.addActionListener(evt -> selectWeapon(14));
        MalikethsBlackBlade.addActionListener(evt -> selectWeapon(15));
        AstrologersStaff.addActionListener(evt -> selectWeapon(16));
        AlbinauricStaff.addActionListener(evt -> selectWeapon(17));
        StaffoftheGuilty.addActionListener(evt -> selectWeapon(18));
        CarianRegalScepter.addActionListener(evt -> selectWeapon(19));
        FingerSeal.addActionListener(evt -> selectWeapon(20));
        GodSlayersSeal.addActionListener(evt -> selectWeapon(21));
        GoldenOrderSeal.addActionListener(evt -> selectWeapon(22));
        DragonCommunionSeal.addActionListener(evt -> selectWeapon(23));
}
    
    private void displayWeaponDetails() {
        if (selectedWeaponIndex >= 0) {
            Weapon weapon = weapons.get(selectedWeaponIndex);
            boolean isOwned = CPlayer.isWeaponOwned(selectedWeaponIndex);
            weapon.setOwned(isOwned);
            InfoStat.setText(weapon.getDetails(weapons));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShortSword = new javax.swing.JButton();
        RogiersRapier = new javax.swing.JButton();
        CodedSword = new javax.swing.JButton();
        SwordofNightandFlame = new javax.swing.JButton();
        Claymore = new javax.swing.JButton();
        StarscourgeGreatsword = new javax.swing.JButton();
        InseparableSword = new javax.swing.JButton();
        MalikethsBlackBlade = new javax.swing.JButton();
        Uchigatana = new javax.swing.JButton();
        Moonveil = new javax.swing.JButton();
        RiversofBlood = new javax.swing.JButton();
        HandofMalenia = new javax.swing.JButton();
        AstrologersStaff = new javax.swing.JButton();
        AlbinauricStaff = new javax.swing.JButton();
        StaffoftheGuilty = new javax.swing.JButton();
        CarianRegalScepter = new javax.swing.JButton();
        ThornedWhip = new javax.swing.JButton();
        HoslowsPetalWhip = new javax.swing.JButton();
        Whip = new javax.swing.JButton();
        Urumi = new javax.swing.JButton();
        FingerSeal = new javax.swing.JButton();
        GodSlayersSeal = new javax.swing.JButton();
        GoldenOrderSeal = new javax.swing.JButton();
        DragonCommunionSeal = new javax.swing.JButton();
        SelectWeapon = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        txtRuneCount = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoStat = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShortSword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Swords/Short Sword.png"))); // NOI18N
        ShortSword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShortSwordActionPerformed(evt);
            }
        });
        getContentPane().add(ShortSword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 100, 140));

        RogiersRapier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Swords/Rogiers Rapier.png"))); // NOI18N
        RogiersRapier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RogiersRapierActionPerformed(evt);
            }
        });
        getContentPane().add(RogiersRapier, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 100, 140));

        CodedSword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Swords/Coded Sword.png"))); // NOI18N
        CodedSword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodedSwordActionPerformed(evt);
            }
        });
        getContentPane().add(CodedSword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 100, 140));

        SwordofNightandFlame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Swords/Sword of Night and Flame.png"))); // NOI18N
        SwordofNightandFlame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwordofNightandFlameActionPerformed(evt);
            }
        });
        getContentPane().add(SwordofNightandFlame, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 100, 140));

        Claymore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/GreatSwords/Claymore.png"))); // NOI18N
        Claymore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaymoreActionPerformed(evt);
            }
        });
        getContentPane().add(Claymore, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 100, 140));

        StarscourgeGreatsword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/GreatSwords/Starscourge Greatsword.png"))); // NOI18N
        StarscourgeGreatsword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarscourgeGreatswordActionPerformed(evt);
            }
        });
        getContentPane().add(StarscourgeGreatsword, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 100, 140));

        InseparableSword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/GreatSwords/Inseparable Sword.png"))); // NOI18N
        InseparableSword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InseparableSwordActionPerformed(evt);
            }
        });
        getContentPane().add(InseparableSword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 140, 100, 140));

        MalikethsBlackBlade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/GreatSwords/Malikeths Black Blade.png"))); // NOI18N
        MalikethsBlackBlade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalikethsBlackBladeActionPerformed(evt);
            }
        });
        getContentPane().add(MalikethsBlackBlade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 140, 100, 140));

        Uchigatana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Katanas/Uchigatana.png"))); // NOI18N
        Uchigatana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UchigatanaActionPerformed(evt);
            }
        });
        getContentPane().add(Uchigatana, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 100, 140));

        Moonveil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Katanas/Moonveil.png"))); // NOI18N
        Moonveil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoonveilActionPerformed(evt);
            }
        });
        getContentPane().add(Moonveil, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 100, 140));

        RiversofBlood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Katanas/Rivers of Blood.png"))); // NOI18N
        RiversofBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiversofBloodActionPerformed(evt);
            }
        });
        getContentPane().add(RiversofBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 100, 140));

        HandofMalenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Katanas/Hand of Malenia.png"))); // NOI18N
        HandofMalenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HandofMaleniaActionPerformed(evt);
            }
        });
        getContentPane().add(HandofMalenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 100, 140));

        AstrologersStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Staves/Astrologers Staff.png"))); // NOI18N
        AstrologersStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AstrologersStaffActionPerformed(evt);
            }
        });
        getContentPane().add(AstrologersStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 100, 140));

        AlbinauricStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Staves/Albinauric Staff.png"))); // NOI18N
        AlbinauricStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlbinauricStaffActionPerformed(evt);
            }
        });
        getContentPane().add(AlbinauricStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 100, 140));

        StaffoftheGuilty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Staves/Staff of the Guilty.png"))); // NOI18N
        StaffoftheGuilty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffoftheGuiltyActionPerformed(evt);
            }
        });
        getContentPane().add(StaffoftheGuilty, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 360, 100, 140));

        CarianRegalScepter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Staves/Carian Regal Scepter.png"))); // NOI18N
        CarianRegalScepter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarianRegalScepterActionPerformed(evt);
            }
        });
        getContentPane().add(CarianRegalScepter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 360, 100, 140));

        ThornedWhip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Whips/Thorned Whip.png"))); // NOI18N
        ThornedWhip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThornedWhipActionPerformed(evt);
            }
        });
        getContentPane().add(ThornedWhip, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 570, 100, 140));

        HoslowsPetalWhip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Whips/Hoslows Petal Whip.png"))); // NOI18N
        HoslowsPetalWhip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoslowsPetalWhipActionPerformed(evt);
            }
        });
        getContentPane().add(HoslowsPetalWhip, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 100, 140));

        Whip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Whips/Whip.png"))); // NOI18N
        Whip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhipActionPerformed(evt);
            }
        });
        getContentPane().add(Whip, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 100, 140));

        Urumi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Whips/Urumi.png"))); // NOI18N
        Urumi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrumiActionPerformed(evt);
            }
        });
        getContentPane().add(Urumi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 100, 140));

        FingerSeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Seals/Finger Seal.png"))); // NOI18N
        FingerSeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FingerSealActionPerformed(evt);
            }
        });
        getContentPane().add(FingerSeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 100, 140));

        GodSlayersSeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Seals/Godslayer Seal.png"))); // NOI18N
        GodSlayersSeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GodSlayersSealActionPerformed(evt);
            }
        });
        getContentPane().add(GodSlayersSeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 100, 140));

        GoldenOrderSeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Seals/Golden Order Seal.png"))); // NOI18N
        GoldenOrderSeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoldenOrderSealActionPerformed(evt);
            }
        });
        getContentPane().add(GoldenOrderSeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 570, 100, 140));

        DragonCommunionSeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Seals/Dragon Communion Seal.png"))); // NOI18N
        DragonCommunionSeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DragonCommunionSealActionPerformed(evt);
            }
        });
        getContentPane().add(DragonCommunionSeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 570, 100, 140));

        SelectWeapon.setBackground(new java.awt.Color(136, 160, 139));
        SelectWeapon.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        SelectWeapon.setForeground(new java.awt.Color(255, 255, 255));
        SelectWeapon.setText("CONFIRM PURCHASE");
        SelectWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectWeaponActionPerformed(evt);
            }
        });
        getContentPane().add(SelectWeapon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 270, 30));

        Back.setBackground(new java.awt.Color(204, 130, 130));
        Back.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 270, 30));

        txtRuneCount.setEditable(false);
        txtRuneCount.setBackground(new java.awt.Color(238, 233, 211));
        txtRuneCount.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        txtRuneCount.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtRuneCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 270, 30));

        InfoStat.setBackground(new java.awt.Color(238, 233, 211));
        InfoStat.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(InfoStat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 270, 330));

        jPanel9.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 120, 110, 10));

        jPanel10.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, 150, 10));

        jPanel11.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 150, 10));

        jPanel12.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 120, 10));

        jPanel13.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 160, 10));

        jPanel15.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 140, 10));

        jPanel16.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 160, 10));

        jPanel17.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 150, 10));

        jPanel18.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 170, 10));

        jPanel14.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 530, 160, -1));

        jPanel19.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 160, -1));

        jPanel20.setBackground(new java.awt.Color(238, 233, 211));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 170, -1));

        jLabel10.setBackground(new java.awt.Color(39, 59, 63));
        jLabel10.setFont(new java.awt.Font("ROG Fonts", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(238, 233, 211));
        jLabel10.setText("GREATSWORDS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, 190, -1));

        jLabel11.setBackground(new java.awt.Color(39, 59, 63));
        jLabel11.setFont(new java.awt.Font("ROG Fonts", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(238, 233, 211));
        jLabel11.setText("STAVES");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, 100, -1));

        jLabel12.setBackground(new java.awt.Color(39, 59, 63));
        jLabel12.setFont(new java.awt.Font("ROG Fonts", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 233, 211));
        jLabel12.setText("SEALS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 520, 80, -1));

        jLabel8.setBackground(new java.awt.Color(39, 59, 63));
        jLabel8.setFont(new java.awt.Font("ROG Fonts", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 233, 211));
        jLabel8.setText("WHIPS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 80, -1));

        jLabel7.setBackground(new java.awt.Color(39, 59, 63));
        jLabel7.setFont(new java.awt.Font("ROG Fonts", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 233, 211));
        jLabel7.setText("KATANAS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 120, -1));

        jLabel6.setBackground(new java.awt.Color(39, 59, 63));
        jLabel6.setFont(new java.awt.Font("ROG Fonts", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 233, 211));
        jLabel6.setText("SWORDS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 100, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 270, 150));
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 78)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 233, 211));
        jLabel4.setText("P");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 50, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 78)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 233, 211));
        jLabel3.setText("S");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 50, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 58)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 233, 211));
        jLabel2.setText("HO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Shop.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShortSwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShortSwordActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_ShortSwordActionPerformed

    private void RogiersRapierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RogiersRapierActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_RogiersRapierActionPerformed

    private void CodedSwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodedSwordActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_CodedSwordActionPerformed

    private void SwordofNightandFlameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwordofNightandFlameActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_SwordofNightandFlameActionPerformed

    private void ClaymoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaymoreActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_ClaymoreActionPerformed

    private void StarscourgeGreatswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarscourgeGreatswordActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_StarscourgeGreatswordActionPerformed

    private void InseparableSwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InseparableSwordActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_InseparableSwordActionPerformed

    private void MalikethsBlackBladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalikethsBlackBladeActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_MalikethsBlackBladeActionPerformed

    private void UchigatanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UchigatanaActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_UchigatanaActionPerformed

    private void MoonveilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoonveilActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_MoonveilActionPerformed

    private void RiversofBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiversofBloodActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_RiversofBloodActionPerformed

    private void HandofMaleniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HandofMaleniaActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_HandofMaleniaActionPerformed

    private void AstrologersStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AstrologersStaffActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_AstrologersStaffActionPerformed

    private void AlbinauricStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlbinauricStaffActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_AlbinauricStaffActionPerformed

    private void StaffoftheGuiltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffoftheGuiltyActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_StaffoftheGuiltyActionPerformed

    private void CarianRegalScepterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarianRegalScepterActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_CarianRegalScepterActionPerformed

    private void WhipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhipActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_WhipActionPerformed

    private void UrumiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrumiActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_UrumiActionPerformed

    private void ThornedWhipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThornedWhipActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_ThornedWhipActionPerformed

    private void HoslowsPetalWhipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoslowsPetalWhipActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_HoslowsPetalWhipActionPerformed

    private void FingerSealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FingerSealActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_FingerSealActionPerformed

    private void GodSlayersSealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GodSlayersSealActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_GodSlayersSealActionPerformed

    private void GoldenOrderSealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoldenOrderSealActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_GoldenOrderSealActionPerformed

    private void DragonCommunionSealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DragonCommunionSealActionPerformed
        displayWeaponDetails();
    }//GEN-LAST:event_DragonCommunionSealActionPerformed

    private void SelectWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectWeaponActionPerformed
    if (selectedWeaponIndex >= 0) {
        Weapon selectedWeapon = weapons.get(selectedWeaponIndex);
        int playerRunes = CPlayer.getRunes();

        if (playerRunes >= selectedWeapon.getCost()) {
            CPlayer.acquireWeapon(selectedWeaponIndex); // Mark weapon as owned
            selectedWeapon.buyWeapon(); // Increase quantity in Weapon class

            // Deduct the cost from player's runes
            CPlayer.spendRunes(selectedWeapon.getCost());
            JOptionPane.showMessageDialog(this, "Weapon purchased: " + selectedWeapon.getName(), "Purchase Successful", JOptionPane.INFORMATION_MESSAGE);
            updateRuneCountDisplay();

        } else {
            JOptionPane.showMessageDialog(this, "Not enough runes to purchase this weapon.", "Purchase Failed", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "No weapon selected.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_SelectWeaponActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GameLobby(CPlayer).setVisible(true);
            this.dispose();
        });
    }//GEN-LAST:event_BackActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlbinauricStaff;
    private javax.swing.JButton AstrologersStaff;
    private javax.swing.JButton Back;
    private javax.swing.JButton CarianRegalScepter;
    private javax.swing.JButton Claymore;
    private javax.swing.JButton CodedSword;
    private javax.swing.JButton DragonCommunionSeal;
    private javax.swing.JButton FingerSeal;
    private javax.swing.JButton GodSlayersSeal;
    private javax.swing.JButton GoldenOrderSeal;
    private javax.swing.JButton HandofMalenia;
    private javax.swing.JButton HoslowsPetalWhip;
    private javax.swing.JTextPane InfoStat;
    private javax.swing.JButton InseparableSword;
    private javax.swing.JButton MalikethsBlackBlade;
    private javax.swing.JButton Moonveil;
    private javax.swing.JButton RiversofBlood;
    private javax.swing.JButton RogiersRapier;
    private javax.swing.JButton SelectWeapon;
    private javax.swing.JButton ShortSword;
    private javax.swing.JButton StaffoftheGuilty;
    private javax.swing.JButton StarscourgeGreatsword;
    private javax.swing.JButton SwordofNightandFlame;
    private javax.swing.JButton ThornedWhip;
    private javax.swing.JButton Uchigatana;
    private javax.swing.JButton Urumi;
    private javax.swing.JButton Whip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtRuneCount;
    // End of variables declaration//GEN-END:variables
}
