/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mco2_ang_balbastro;

/**
 * Displays the Stormveil Castle area.
 * 
 * @author ANG, JEREMIAH MAXWELL
 * @author BALBASTRO, LIANNE MAXENE
 * @version 2.0
 */
public class StormveilCastle extends Area{
    /**
     * Sole constructor.
     * Requires Player upon creation.
     * Creates new form StormveilCastle
     * @param CPlayer
     */
    public StormveilCastle(Player CPlayer) {
        super(3, CPlayer, 1, "Stormveil Castle");
        initComponents();
        
        
        createLabelList();
        this.fmFloor1.setVisible(true);
        
        
        //from the Area parent
        //int parameters: floor num, # of fast, # of spawn, # of boss, # of door
        generateFloor(0, 1, 2, 0, 1);
        generateFloor(1, 0, 8, 0, 2);
        generateFloor(2, 1, 0, 1, 1);
        
        
        associateLabels(this.nFloorCount); //from the Area parent
        initializeKeyListener();  
        
        this.fmFloor1.setFocusable(true);
        this.fmFloor1.requestFocusInWindow();  
        
    }
    
    private void createLabelList(){
        //List of Floor JFrames
        this.CFloors.get(0).setFloorFrames(fmFloor1);
        this.CFloors.get(0).getFloorBack().add(labFloorBack1);
        
        this.CFloors.get(1).setFloorFrames(fmFloor2);
        this.CFloors.get(1).getFloorBack().add(labFloorBack2);
        
        this.CFloors.get(2).setFloorFrames(fmFloor3);
        this.CFloors.get(2).getFloorBack().add(labFloorBack3);
        
        addScreenDetails(this.CFloors);
        
        //List of Tile JLabels
        
        //Floor 1
        this.CFloors.get(0).getTileLabels().add(labFast1);
        this.CFloors.get(0).getTileLabels().add(labSpawn1A);
        this.CFloors.get(0).getTileLabels().add(labSpawn1B);
        this.CFloors.get(0).getTileLabels().add(labDoor1A); //3
        
        //Floor 2
        this.CFloors.get(1).getTileLabels().add(labSpawn2A);
        this.CFloors.get(1).getTileLabels().add(labSpawn2B);
        this.CFloors.get(1).getTileLabels().add(labSpawn2C);
        this.CFloors.get(1).getTileLabels().add(labSpawn2D);
        this.CFloors.get(1).getTileLabels().add(labSpawn2E);
        this.CFloors.get(1).getTileLabels().add(labSpawn2F);
        this.CFloors.get(1).getTileLabels().add(labSpawn2G);
        this.CFloors.get(1).getTileLabels().add(labSpawn2H);
        this.CFloors.get(1).getTileLabels().add(labDoor2A); //8
        this.CFloors.get(1).getTileLabels().add(labDoor2B); //9
        
        //Floor 3
        this.CFloors.get(2).getTileLabels().add(labFast2);
        this.CFloors.get(2).getTileLabels().add(labBoss);
        this.CFloors.get(2).getTileLabels().add(labDoor3A); //2
        
        
        
        //List of Player Sprite JLabels
        this.labPlayer1.setLocation(620, 520);
        this.CFloors.get(0).setPlayerSprite(this.labPlayer1);
        
        this.labPlayer2.setLocation(390, 420);
        this.CFloors.get(1).setPlayerSprite(this.labPlayer2);
        
        this.labPlayer3.setLocation(620, 520);
        this.CFloors.get(2).setPlayerSprite(this.labPlayer3);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fmFloor3 = new javax.swing.JFrame();
        labPlayer3 = new javax.swing.JLabel();
        labBoss = new javax.swing.JLabel();
        labFast2 = new javax.swing.JLabel();
        labDoor3A = new javax.swing.JLabel();
        labFloorBack3 = new javax.swing.JLabel();
        labBackground3 = new javax.swing.JLabel();
        fmFloor2 = new javax.swing.JFrame();
        labPlayer2 = new javax.swing.JLabel();
        labDoor2B = new javax.swing.JLabel();
        labSpawn2H = new javax.swing.JLabel();
        labSpawn2G = new javax.swing.JLabel();
        labSpawn2C = new javax.swing.JLabel();
        labSpawn2F = new javax.swing.JLabel();
        labSpawn2D = new javax.swing.JLabel();
        labSpawn2E = new javax.swing.JLabel();
        labSpawn2B = new javax.swing.JLabel();
        labSpawn2A = new javax.swing.JLabel();
        labDoor2A = new javax.swing.JLabel();
        labFloorBack2 = new javax.swing.JLabel();
        labBackground2 = new javax.swing.JLabel();
        fmFloor1 = new javax.swing.JFrame();
        labPlayer1 = new javax.swing.JLabel();
        labDoor1A = new javax.swing.JLabel();
        labFast1 = new javax.swing.JLabel();
        labSpawn1A = new javax.swing.JLabel();
        labSpawn1B = new javax.swing.JLabel();
        labFloorBack1 = new javax.swing.JLabel();
        labBackground1 = new javax.swing.JLabel();

        fmFloor3.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        fmFloor3.setForeground(new java.awt.Color(0, 0, 0));
        fmFloor3.setMinimumSize(new java.awt.Dimension(830, 569));
        fmFloor3.setSize(new java.awt.Dimension(830, 569));
        fmFloor3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer3.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer3.setAlignmentY(0.0F);
        labPlayer3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer3.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor3.getContentPane().add(labPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 50, 60));

        labBoss.setBackground(new java.awt.Color(255, 255, 255));
        labBoss.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labBoss.setForeground(new java.awt.Color(102, 102, 102));
        labBoss.setText("    B");
        labBoss.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(181, 103, 103), 5));
        labBoss.setOpaque(true);
        labBoss.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labBoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 60, 60));

        labFast2.setBackground(new java.awt.Color(255, 255, 255));
        labFast2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFast2.setForeground(new java.awt.Color(102, 102, 102));
        labFast2.setText("    F^");
        labFast2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 122, 96), 5));
        labFast2.setMaximumSize(new java.awt.Dimension(50, 50));
        labFast2.setMinimumSize(new java.awt.Dimension(50, 50));
        labFast2.setOpaque(true);
        labFast2.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labFast2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 60, 60));

        labDoor3A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor3A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor3A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor3A.setText("    D");
        labDoor3A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor3A.setOpaque(true);
        labDoor3A.setPreferredSize(new java.awt.Dimension(75, 75));
        fmFloor3.getContentPane().add(labDoor3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 60, 60));

        labFloorBack3.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack3.setForeground(new java.awt.Color(102, 102, 102));
        labFloorBack3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(149, 168, 154), 5));
        labFloorBack3.setOpaque(true);
        labFloorBack3.setPreferredSize(new java.awt.Dimension(375, 225));
        fmFloor3.getContentPane().add(labFloorBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 300, 420));

        labBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/StormveilCastleBg.jpg"))); // NOI18N
        fmFloor3.getContentPane().add(labBackground3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        fmFloor2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        fmFloor2.setForeground(new java.awt.Color(0, 0, 0));
        fmFloor2.setMinimumSize(new java.awt.Dimension(830, 569));
        fmFloor2.setSize(new java.awt.Dimension(830, 569));
        fmFloor2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPlayer2.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer2.setAlignmentY(0.0F);
        labPlayer2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer2.setMinimumSize(new java.awt.Dimension(60, 60));
        labPlayer2.setPreferredSize(new java.awt.Dimension(55, 55));
        fmFloor2.getContentPane().add(labPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 50, -1));

        labDoor2B.setBackground(new java.awt.Color(255, 255, 255));
        labDoor2B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor2B.setForeground(new java.awt.Color(102, 102, 102));
        labDoor2B.setText("    D");
        labDoor2B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor2B.setOpaque(true);
        labDoor2B.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labDoor2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        labSpawn2H.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2H.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2H.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2H.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn2H.setText("?");
        labSpawn2H.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2H.setOpaque(true);
        labSpawn2H.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labSpawn2H, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        labSpawn2G.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2G.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2G.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2G.setText("     ?");
        labSpawn2G.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2G.setOpaque(true);
        labSpawn2G.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labSpawn2G, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        labSpawn2C.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2C.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2C.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2C.setText("     ?");
        labSpawn2C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2C.setOpaque(true);
        labSpawn2C.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labSpawn2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        labSpawn2F.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2F.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2F.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2F.setText("    ?");
        labSpawn2F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2F.setOpaque(true);
        labSpawn2F.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labSpawn2F, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        labSpawn2D.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2D.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2D.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn2D.setText("?");
        labSpawn2D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2D.setOpaque(true);
        labSpawn2D.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labSpawn2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        labSpawn2E.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2E.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2E.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2E.setText("     ?");
        labSpawn2E.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2E.setOpaque(true);
        labSpawn2E.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labSpawn2E, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        labSpawn2B.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2B.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2B.setText("    ?");
        labSpawn2B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2B.setOpaque(true);
        labSpawn2B.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labSpawn2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        labSpawn2A.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn2A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn2A.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn2A.setText("    ?");
        labSpawn2A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn2A.setOpaque(true);
        labSpawn2A.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labSpawn2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        labDoor2A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor2A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor2A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor2A.setText("    D");
        labDoor2A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor2A.setOpaque(true);
        labDoor2A.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor2.getContentPane().add(labDoor2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        labFloorBack2.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack2.setForeground(new java.awt.Color(102, 102, 102));
        labFloorBack2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(149, 168, 154), 5));
        labFloorBack2.setOpaque(true);
        labFloorBack2.setPreferredSize(new java.awt.Dimension(420, 420));
        fmFloor2.getContentPane().add(labFloorBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        labBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/StormveilCastleBg.jpg"))); // NOI18N
        fmFloor2.getContentPane().add(labBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 570));

        fmFloor1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        fmFloor1.setBackground(new java.awt.Color(0, 0, 0));
        fmFloor1.setForeground(new java.awt.Color(0, 0, 0));
        fmFloor1.setMinimumSize(new java.awt.Dimension(830, 569));
        fmFloor1.setSize(new java.awt.Dimension(830, 569));
        fmFloor1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fmFloor1.getContentPane().add(labPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        labPlayer1.setBackground(new java.awt.Color(153, 153, 153));
        labPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/Player_Sprite.png"))); // NOI18N
        labPlayer1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labPlayer1.setAlignmentY(0.0F);
        labPlayer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labPlayer1.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor1.getContentPane().add(labPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 50, 55));

        labDoor1A.setBackground(new java.awt.Color(255, 255, 255));
        labDoor1A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labDoor1A.setForeground(new java.awt.Color(102, 102, 102));
        labDoor1A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDoor1A.setText("D");
        labDoor1A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 175, 87), 5));
        labDoor1A.setOpaque(true);
        labDoor1A.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor1.getContentPane().add(labDoor1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        labFast1.setBackground(new java.awt.Color(255, 255, 255));
        labFast1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFast1.setForeground(new java.awt.Color(102, 102, 102));
        labFast1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labFast1.setText("F^");
        labFast1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 122, 96), 5));
        labFast1.setMaximumSize(new java.awt.Dimension(50, 50));
        labFast1.setMinimumSize(new java.awt.Dimension(50, 50));
        labFast1.setOpaque(true);
        labFast1.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor1.getContentPane().add(labFast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        labSpawn1A.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn1A.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn1A.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn1A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn1A.setText("?");
        labSpawn1A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn1A.setOpaque(true);
        labSpawn1A.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor1.getContentPane().add(labSpawn1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        labSpawn1B.setBackground(new java.awt.Color(255, 255, 255));
        labSpawn1B.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labSpawn1B.setForeground(new java.awt.Color(102, 102, 102));
        labSpawn1B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSpawn1B.setText("?");
        labSpawn1B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 114, 150), 5));
        labSpawn1B.setOpaque(true);
        labSpawn1B.setPreferredSize(new java.awt.Dimension(60, 60));
        fmFloor1.getContentPane().add(labSpawn1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        labFloorBack1.setBackground(new java.awt.Color(204, 204, 204));
        labFloorBack1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        labFloorBack1.setForeground(new java.awt.Color(204, 204, 204));
        labFloorBack1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labFloorBack1.setAlignmentY(0.0F);
        labFloorBack1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(149, 168, 154), 5));
        labFloorBack1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labFloorBack1.setOpaque(true);
        labFloorBack1.setPreferredSize(new java.awt.Dimension(180, 420));
        fmFloor1.getContentPane().add(labFloorBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        labBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mco2_ang_balbastro/Backgrounds/StormveilCastleBg.jpg"))); // NOI18N
        fmFloor1.getContentPane().add(labBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 570));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(830, 569));
        setSize(new java.awt.Dimension(830, 569));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.dispose();
    }//GEN-LAST:event_formWindowOpened

    
    /**
     * Checks the Player's current floor before using the appropriate door, areas have individual implementations.
     */
    public void checkDoor(){
        int lvl = CPlayer.getCurrentFloor();
        
        switch(lvl){
            case 0:
                useDoor(0, 1, 3, false);
                break;
            case 1:
                useDoor(1, -1, 8, true); //go back to Floor 1
                useDoor(1, 1, 9, false);
                break;
            case 2:
                useDoor(2, -1, 2, true); //go back to Floor 2
        }
        
    } //end of checkDoor()
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame fmFloor1;
    private javax.swing.JFrame fmFloor2;
    private javax.swing.JFrame fmFloor3;
    private javax.swing.JLabel labBackground1;
    private javax.swing.JLabel labBackground2;
    private javax.swing.JLabel labBackground3;
    private javax.swing.JLabel labBoss;
    private javax.swing.JLabel labDoor1A;
    private javax.swing.JLabel labDoor2A;
    private javax.swing.JLabel labDoor2B;
    private javax.swing.JLabel labDoor3A;
    private javax.swing.JLabel labFast1;
    private javax.swing.JLabel labFast2;
    private javax.swing.JLabel labFloorBack1;
    private javax.swing.JLabel labFloorBack2;
    private javax.swing.JLabel labFloorBack3;
    private javax.swing.JLabel labPlayer1;
    private javax.swing.JLabel labPlayer2;
    private javax.swing.JLabel labPlayer3;
    private javax.swing.JLabel labSpawn1A;
    private javax.swing.JLabel labSpawn1B;
    private javax.swing.JLabel labSpawn2A;
    private javax.swing.JLabel labSpawn2B;
    private javax.swing.JLabel labSpawn2C;
    private javax.swing.JLabel labSpawn2D;
    private javax.swing.JLabel labSpawn2E;
    private javax.swing.JLabel labSpawn2F;
    private javax.swing.JLabel labSpawn2G;
    private javax.swing.JLabel labSpawn2H;
    // End of variables declaration//GEN-END:variables
}
